### ISSUE TITLE
okonomiyaki doesn't work with the latest jsonschema, 3.0.0

### ISSUE THREAD

**Issue by kihneman** [enthought/okonomiyaki#317]
The error and traceback can be seen in https://github.com/enthought/okonomiyaki/issues/315.

This was fixed temporarily in https://github.com/enthought/okonomiyaki/pull/316 by not using the latest version of `jsonschema`, 3.0.0.

It may be that this issue will be fixed in subsequent bug fixes in either `jsonschema` or `attrs`.

**Comment by itziakos** [comment]
@kihneman, In a number of places (including the buildsystem repos) we are installing packages from pip so if the current released version of okonomiyaki does not support jsonschema > 3.0.0 it might cause unexpected errors. We should fix the compatibility before the next okonomiyaki release.
