### ISSUE TITLE
Travis ci should run on PRs against maintenance branches

### ISSUE THREAD

**Issue by itziakos** [enthought/okonomiyaki#352]
Currently travis-ci is not running when the PR is against a maintenance branch

**Comment by kihneman** [comment]
@itziakos, it looks like travis-ci is running to me on #355 and #356. What am I missing?

**Comment by itziakos** [comment]
> 
> 
> @itziakos, it looks like travis-ci is running to me on #355 and #356. What am I missing?

You PR is against `master` not a `maintenance/` branch
