### ISSUE TITLE
Run tests against centos 7

### ISSUE THREAD

**Issue by itziakos** [enthought/okonomiyaki#359]

**Comment by kihneman** [comment]
I successfully tested on centos 7 manually. I imagine that you are probably wanting a Jenkins job to test on centos 7, though.

**Comment by itziakos** [comment]
> 
> 
> I successfully tested on centos 7 manually. I imagine that you are probably wanting a Jenkins job to test on centos 7, though.

Yes, we need to add centos 7 builds into our jenkins pr build.
