### ISSUE TITLE
Okonomiyaki fails to parse egg metadata for RegistryPath-1.0-1

### ISSUE THREAD

**Issue by sjagoe** [enthought/okonomiyaki#87]
okonomiyaki no longer handles eggs where the `arch` and `osdist` are `None` in `spec/depend`, but `platform` is _not_ `None`.

spec/depend: 
```python
metadata_version = '1.1'
name = 'RegistryPath'
version = '1.0'
build = 1

arch = None
platform = 'win32'
osdist = None
python = '2.7'
packages = [
  'pywin32 214',
]
```

**Comment by cournape** [comment]
Hm, so the issue is that okonomiyaki does not support the notion of platform without a specific arch (e.g. `win-any` instead of `win-x86` or `win-x86_64`).

**Comment by cournape** [comment]
Thinking more about it, supporting the notion of platform without an arch would require quite a bit of work across the infrastructure (not just okonomiyaki), so I think I would rather treat this case a black list case as well.

**Comment by cournape** [comment]
We ended up removing this egg and others with similar problems, as the same egg was put on different platforms, hence no way to distinguish them.
